# -*- coding: utf-8 -*-
"""ICP2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CyUQ2s6ClKX6_A87nh-mK_D68E94Sg1h
"""

#question 1
for j in range(1,6):
  print('\n')
  for i in range(1,j+1):
    print("*" ,end=" ")
    i=i-1
for k in range(j-1,0,-1):
  print('\n')
  for i in range(1,k+1):
    print("*" ,end=" ")
    i=i-1

'''question 2 Use looping to output the elements from a provided list present at odd indexes.
my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]'''

my_list = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
for i in range(1,len(my_list),2):
  print(my_list[i])

'''question 3 Write a code that appends the type of elements from a given list.
Input
x = [23, ‘Python’, 23.98]
Expected output
[23, 'Python', 23.98]
[<class 'int'>, <class 'str'>, <class 'float'>]
'''
x = [23, 'Python', 23.98]
type_list=[]
for i in x:
  type_list.append(type(i))
print(x)
print(type_list)

'''question 4 Write a function that takes a list and returns a new list with unique items of the first list.
Sample List: [1,2,3,3,3,3,4,5]
Unique List: [1, 2, 3, 4, 5]'''
n=input('enter the list ')
sample_list=[]
for i in n.split(' '): sample_list.append(i)
unique_list=list(set(sample_list))
print("sample list: ", sample_list)
print("unique list: ", unique_list)

'''question 5 Write a function that accepts a string and calculate the number of upper-case letters and lower-case
letters.
Input String: 'The quick Brow Fox'
Expected Output:
No. of Upper-case characters: 3
No. of Lower-case Characters: 12'''
input_string=input('enter the input string: ')
upper=0
lower=0
for i in input_string:
  if i.isupper():
    upper+=1
  elif i.islower():
    lower+=1
print('No. of Upper-case characters: ', upper)
print('No. of Lower-case Characters: ', lower)